export const GET_DATA_REQUEST = "GET_DATA_REQUEST"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAILURE = "GET_DATA_FAILURE"

export const GET_DATA_REQUEST2 = "GET_DATA_REQUEST2"
export const GET_DATA_SUCCESS2 = "GET_DATA_SUCCESS2"
export const GET_DATA_FAILURE2 = "GET_DATA_FAILURE2"

export const GET_DATA_REQUEST3 = "GET_DATA_REQUEST3"
export const GET_DATA_SUCCESS3 = "GET_DATA_SUCCESS3"
export const GET_DATA_FAILURE3 = "GET_DATA_FAILURE3"

export const GET_DATA_REQUEST4 = "GET_DATA_REQUEST4"
export const GET_DATA_SUCCESS4 = "GET_DATA_SUCCESS4"
export const GET_DATA_FAILURE4 = "GET_DATA_FAILURE4"

export const GET_DATA_REQUEST5 = "GET_DATA_REQUEST5"
export const GET_DATA_SUCCESS5 = "GET_DATA_SUCCESS5"
export const GET_DATA_FAILURE5 = "GET_DATA_FAILURE5"

export const GET_DATA_REQUEST6 = "GET_DATA_REQUEST6"
export const GET_DATA_SUCCESS6 = "GET_DATA_SUCCESS6"
export const GET_DATA_FAILURE6 = "GET_DATA_FAILURE6"

export const GET_DATA_REQUEST7 = "GET_DATA_REQUEST7"
export const GET_DATA_SUCCESS7 = "GET_DATA_SUCCESS7"
export const GET_DATA_FAILURE7 = "GET_DATA_FAILURE7"

export const GET_DATA_REQUEST8 = "GET_DATA_REQUEST8"
export const GET_DATA_SUCCESS8 = "GET_DATA_SUCCESS8"
export const GET_DATA_FAILURE8 = "GET_DATA_FAILURE8"

export const GET_DATA_REQUEST9 = "GET_DATA_REQUEST9"
export const GET_DATA_SUCCESS9 = "GET_DATA_SUCCESS9"
export const GET_DATA_FAILURE9 = "GET_DATA_FAILURE9"


//-------------------------Ravi-----------------------------------------------

export const REQUEST_PACKAGE_DATA = "REQUEST_PACKAGE_DATA";
export const SUCCESS_PACKAGE_DATA = "SUCCESS_PACKAGE_DATA";
export const FAILURE_PACKAGE_DATA = "FAILURE_PACKAGE_DATA";

export const REQUEST_PACKAGE_DATA_MIND = "REQUEST_PACKAGE_DATA_MIND";
export const SUCCESS_PACKAGE_DATA_MIND = "SUCCESS_PACKAGE_DATA_MIND";
export const FAILURE_PACKAGE_DATA_MIND = "FAILURE_PACKAGE_DATA_MIND";

export const REQUEST_PACKAGE_DATA_DOMESTIC = "REQUEST_PACKAGE_DATA_DOMESTIC";
export const SUCCESS_PACKAGE_DATA_DOMESTIC = "SUCCESS_PACKAGE_DATA_DOMESTIC";
export const FAILURE_PACKAGE_DATA_DOMESTIC = "FAILURE_PACKAGE_DATA_DOMESTIC";

export const REQUEST_PACKAGE_DATA_INTERNATIONAL = "REQUEST_PACKAGE_DATA_INTERNATIONAL";
export const SUCCESS_PACKAGE_DATA_INTERNATIONAL = "SUCCESS_PACKAGE_DATA_INTERNATIONAL";
export const FAILURE_PACKAGE_DATA_INTERNATIONAL = "FAILURE_PACKAGE_DATA_INTERNATIONAL";

export const GET_SINGLE_PACKAGE_DATA = "GET_SINGLE_PACKAGE_DATA";
export const SUCCESS_SINGLE_PACKAGE_DATA = "SUCCESS_SINGLE_PACKAGE_DATA";
export const ERROR_SINGLE_PACKAGE_DATA = "ERROR_SINGLE_PACKAGE_DATA";