export const GET_DATA_REQUEST = "GET_DATA_REQUEST"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAILURE = "GET_DATA_FAILURE"

export const GET_DATA_REQUEST2 = "GET_DATA_REQUEST2"
export const GET_DATA_SUCCESS2 = "GET_DATA_SUCCESS2"
export const GET_DATA_FAILURE2 = "GET_DATA_FAILURE2"