export const REQUEST_PACKAGE_DATA = "REQUEST_PACKAGE_DATA";
export const SUCCESS_PACKAGE_DATA = "SUCCESS_PACKAGE_DATA";
export const FAILURE_PACKAGE_DATA = "FAILURE_PACKAGE_DATA";

export const REQUEST_PACKAGE_DATA_MIND = "REQUEST_PACKAGE_DATA_MIND";
export const SUCCESS_PACKAGE_DATA_MIND = "SUCCESS_PACKAGE_DATA_MIND";
export const FAILURE_PACKAGE_DATA_MIND = "FAILURE_PACKAGE_DATA_MIND";

export const REQUEST_PACKAGE_DATA_DOMESTIC = "REQUEST_PACKAGE_DATA_DOMESTIC";
export const SUCCESS_PACKAGE_DATA_DOMESTIC = "SUCCESS_PACKAGE_DATA_DOMESTIC";
export const FAILURE_PACKAGE_DATA_DOMESTIC = "FAILURE_PACKAGE_DATA_DOMESTIC";

export const REQUEST_PACKAGE_DATA_INTERNATIONAL = "REQUEST_PACKAGE_DATA_INTERNATIONAL";
export const SUCCESS_PACKAGE_DATA_INTERNATIONAL = "SUCCESS_PACKAGE_DATA_INTERNATIONAL";
export const FAILURE_PACKAGE_DATA_INTERNATIONAL = "FAILURE_PACKAGE_DATA_INTERNATIONAL";

export const GET_SINGLE_PACKAGE_DATA = "GET_SINGLE_PACKAGE_DATA";
export const SUCCESS_SINGLE_PACKAGE_DATA = "SUCCESS_SINGLE_PACKAGE_DATA";
export const ERROR_SINGLE_PACKAGE_DATA = "ERROR_SINGLE_PACKAGE_DATA";